apiVersion: v1
kind: Service
metadata:
  name: kubesentinel
  namespace: kubesentinel
  labels:
    app.kubernetes.io/name: kubesentinel
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kubesentinel
  ports:
    - name: http
      port: 80
      targetPort: http
